In [4]:
import pandas as pd
data={'marks':[1,1,2,2,3,3],
              'test1':[15,16,2,2,5,16]}
data1=pd.DataFrame(data)

In [5]:
data1

   marks  test1
0      1     15
1      1     16
2      2      2
3      2      2
4      3      5
5      3     16

In [6]:
data1.duplicated(data)

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [15]:
data1.drop_duplicates()

   marks  test1
0      1     15
1      1     16
2      2      2
4      3      5
5      3     16

In [17]:
data1.drop_duplicates('test1')

   marks  test1
0      1     15
1      1     16
2      2      2
4      3      5

In [18]:
import pandas as pd
df=pd.read_csv("school1.csv")

In [19]:
df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,INSTURL,NPCURL,HCM2,PREDDEG,...,RET_PTL4_POOLED_SUPP,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
0,100654,100200,1002,Alabama A & M University,Normal,AL,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,0,3,...,NaN,0.8159,0.0877,29900,0.453,35000,361.891446885773,0.2458495231,NaN,0.3303
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,0,3,...,NaN,0.5218,0.2363,40200,0.669,21500,222.304745944118,0.5199110572,NaN,0.5504
2,100690,2503400,25034,Amridge University,Montgomery,AL,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,0,3,...,NaN,0.8781,0.8571,40100,0.658,23000,237.814379382079,0.2331002331,NaN,PrivacySuppressed
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,www.uah.edu,finaid.uah.edu/,0,3,...,NaN,0.4589,0.2255,45600,0.685,23500,242.984257194733,0.5490029699,NaN,0.4776
4,100724,100500,1005,Alabama State University,Montgomery,AL,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,0,3,...,NaN,0.7692,0.0974,26700,0.393,32091,331.813097771753,0.1963538553,NaN,0.2663
5,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,0,3,...,NaN,0.4059,0.0810,42700,0.695,23750,245.56919610106,0.5911430119,NaN,0.6638
6,100760,100700,1007,Central Alabama Community College,Alexander City,AL,www.cacc.edu,www.cacc.edu/NetPriceCalculator/14-15/npcalc.html,0,2,...,0.51948376623376,0.3574,0.2630,27200,0.466,9388,97.0696258103897,0.263502455,0.1722,NaN
7,100812,100800,1008,Athens State University,Athens,AL,www.athens.edu,https://24.athens.edu/apex/prod8/f?p=174:1:394...,0,3,...,NaN,0.6512,0.6774,38500,0.653,18534,191.637030759455,0.4942462601,NaN,NaN
8,100830,831000,8310,Auburn University at Montgomery,Montgomery,AL,www.aum.edu,www.aum.edu/current-students/financial-informa...,0,3,...,NaN,0.5584,0.2257,33500,0.616,22192.5,229.465026714643,0.4162696959,NaN,0.2115
9,100858,100900,1009,Auburn University,Auburn,AL,www.auburn.edu,www.auburn.edu/admissions/money-matters.html,0,3,...,NaN,0.3470,0.0427,47100,0.741,21500,222.304745944118,0.731666973,NaN,0.7188
10,100937,101200,1012,Birmingham Southern College,Birmingham,AL,www.bsc.edu/,www.bsc.edu/fp/np-calculator.cfm,0,3,...,NaN,0.4633,0.0141,45600,0.637,26850,277.622438539514,0.747826087,NaN,0.627
11,101028,1218200,12182,Chattahoochee Valley Community College,Phenix City,AL,www.cv.edu,https://external.cv.edu/npc/npcalc.htm,0,2,...,0.25830463576158,0.3058,0.3604,26300,0.41,9389.5,97.0851354438277,0.2684824903,0.1376,NaN
12,101073,1055400,10554,Concordia College Alabama,Selma,AL,www.ccal.edu/,www.ccal.edu/admissions/net-pricing-calculator/,0,2,...,NaN,0.9249,0.1294,20600,0.356,36870,381.226789905099,0.1184834123,NaN,0.1458
13,101116,1303906,13039,South University-Montgomery,Montgomery,AL,www.southuniversity.edu/montgomery#location=Mo...,tcc.noellevitz.com/edmc/South Net Price Calcul...,0,3,...,NaN,0.7304,0.6109,30300,0.58,25000,258.493890632695,0.226137931,NaN,0.0792
14,101143,101500,1015,Enterprise State Community College,Enterprise,AL,www.escc.edu,www.escc.edu/NetPrice/npcalc.htm,0,2,...,0.36528502994011,0.2128,0.2896,29800,0.518,7155,73.9809514990774,0.4375634518,0.1026,NaN
15,101161,106000,1060,James H Faulkner State Community College,Bay Minette,AL,www.faulknerstate.edu,www.faulknerstate.edu,0,2,...,0.3501181619256,0.5107,0.2598,28700,0.475,11000,113.737311878385,0.3568502503,0.1146,NaN
16,101189,100300,1003,Faulkner University,Montgomery,AL,www.faulkner.edu,www.faulkner.edu/net-price-calculator-form/,0,3,...,NaN,0.7105,0.4353,35900,0.614,21750,224.889684850445,0.3014899211,NaN,0.2553
17,101240,101700,1017,Gadsden State Community College,Gadsden,AL,www.gadsdenstate.edu,www.gadsdenstate.edu/net-price-calculator,0,1,...,0.43215794573643,0.0000,0.3320,25400,0.379,PrivacySuppressed,PrivacySuppressed,NaN,0.1568,NaN
18,101277,4187200,41872,New Beginning College of Cosmetology,Albertville,AL,www.nbccosmetology.com,www.nbccosmetology.com/npcalc.htm,0,1,...,PrivacySuppressed,0.5749,0.2747,NaN,NaN,5500,56.8686559391929,0.4,0.7155,NaN
19,101286,101800,1018,George C Wallace State Community College-Dothan,Dothan,AL,www.wallace.edu,www.wallace.edu/net_price_calculator.aspx,0,2,...,0.43297406593406,0.0000,0.3422,24800,0.374,PrivacySuppressed,PrivacySuppressed,NaN,0.1721,NaN
20,101295,787100,7871,George C Wallace State Community College-Hance...,Hanceville,AL,www.wallacestate.edu,www.wallacestate.edu/Financial-Aid/Net-Price-C...,0,2,...,0.45582165242165,0.3915,0.2671,31100,0.537,11000,113.737311878385,0.4402676011,0.2923,NaN
21,101301,569900,5699,George C Wallace State Community College-Selma,Selma,AL,www.wccs.edu,wccs.edu/home/admissions/financial-aid/net-pri...,0,2,...,0.391665,0.0000,0.2753,23100,0.376,PrivacySuppressed,PrivacySuppressed,NaN,0.1879,NaN
22,101365,962107,9621,Herzing University-Birmingham,Birmingham,AL,www.herzing.edu/,www.herzing.edu/financial-aid/net-price-calcul...,0,1,...,NaN,0.7219,0.7147,40300,0.566,23713.5,245.191795020736,0.2771250864,NaN,0.4118
23,101435,101900,1019,Huntingdon College,Montgomery,AL,www.huntingdon.edu,hawk.huntingdon.edu/oiac/netpricecalculator/np...,0,3,...,NaN,0.6862,0.2196,36800,0.612,26477.5,273.770879569087,0.4992657856,NaN,0.4327
24,101453,2199700,21997,Heritage Christian University,Florence,AL,www.hcu.edu,www.hcu.edu/netpricecalculator/,0,3,...,NaN,0.3226,0.5862,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,NaN,PrivacySuppressed
25,101462,526000,5260,J F Drake State Community and Technical College,Huntsville,AL,www.drakestate.edu,www.drakestate.edu/admissions/net_price_calcul...,0,2,...,0.25640064102564,0.0000,0.4769,22200,0.369,PrivacySuppressed,PrivacySuppressed,NaN,0.1246,NaN
26,101480,102000,1020,Jacksonville State University,Jacksonville,AL,www.jsu.edu/,www.jsu.edu/finaid/,0,3,...,NaN,0.6746,0.1814,35000,0.548,23250,240.399318288406,0.3945111492,NaN,0.3057
27,101499,102100,1021,Jefferson Davis Community College,Brewton,AL,www.jdcc.edu,www.jdcc.edu/netpricecalculator/,0,2,...,0.42859238095238,0.0000,0.3843,24100,0.452,PrivacySuppressed,PrivacySuppressed,NaN,0.2427,NaN
28,101505,102200,1022,Jefferson State Community College,Birmingham,AL,www.jeffstateonline.com,www.jeffersonstate.edu/financial-aid/net-price...,0,2,...,0.44684917891097,0.2156,0.3118,30100,0.534,8500,87.8879228151164,0.4520738933,0.0609,NaN
29,101514,101300,1013,John C Calhoun State Community College,Tanner,AL,www.calhoun.edu,https://calhoun.edu/student-resources/financia...,0,2,...,0.43881048689138,0.2877,0.3488,27300,0.454,11000,113.737311878385,0.3851002865,0.1408,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7563,45891902,145946,1459,Strayer University-Morrow Campus,Morrow,GA,www.strayer.edu/georgia/morrow,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7564,45891903,145952,1459,Strayer University-Roswell Campus,Roswell,GA,www.strayer.edu/georgia/roswell,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7565,45891904,145959,1459,Strayer University-Douglasville Campus,Douglasville,GA,www.strayer.edu/georgia/douglasville,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7566,45891905,145965,1459,Strayer University-Lithonia Campus,Lithonia,GA,www.strayer.edu/georgia/lithonia,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7567,45891906,145971,1459,Strayer University-Savannah Campus,Savannah,GA,www.strayer.edu/georgia/savannah,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7568,45891907,145972,1459,Strayer University-Augusta Campus,Augusta,GA,www.strayer.edu/georgia/augusta,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7569,45891908,145996,1459,Strayer University-Columbus,Columbus,GA,www.strayer.edu/georgia/columbus,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7570,45896401,145945,1459,Strayer University-Columbia Campus,Columbia,SC,www.strayer.edu/south-carolina/columbia,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7571,45896402,145954,1459,Strayer University-Charleston Campus,North Charleston,SC,www.strayer.edu/south-carolina/charleston,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7572,45897301,145990,1459,Strayer University-Irving,Irving,TX,www.strayer.edu/texas/irving,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7573,45897302,145992,1459,Strayer University-Katy,Houston,TX,www.strayer.edu/texas/katy,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7574,45897303,145994,1459,Strayer University-Northwest Houston,Houston,TX,www.strayer.edu/texas/northwest-houston,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7575,45897304,145995,1459,Strayer University-Plano,Plano,TX,www.strayer.edu/texas/plano,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7576,45897305,10145900,1459,Strayer University-Cedar Hill,Cedar Hill,TX,www.strayer.edu/texas/cedar-hill,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7577,45897306,10145901,1459,Strayer University-North Dallas,Dallas,TX,www.strayer.edu/texas/north-dallas,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7578,45897307,10145908,1459,Strayer University-San Antonio,San Antonio,TX,www.strayer.edu/texas/san-antonio,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7579,45897308,10145909,1459,Strayer University-Stafford,Stafford,TX,www.strayer.edu/texas/stafford,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
7580,45920401,4169701,41697,Unitek College,Fremont,CA,www.unitekcollege.edu/,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,9500,98.2276784404242,0.6731391586,NaN,NaN
7581,47503301,4208601,42086,Relay Graduate School of Education - Newark,Newark,NJ,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
7582,47503302,4208602,42086,Relay Graduate School of Education - New Orleans,New Orleans,LA,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
7583,47647001,4088301,40883,WestMed College - Merced,Merced,CA,www.westmedcollege.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,10093,104.359153526231,0.5555555556,NaN,NaN
7584,47657701,4184801,41848,Vantage College,El Paso,TX,www.vantage.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,9500,98.2276784404242,PrivacySuppressed,NaN,NaN
7585,47657702,4184802,41848,Vantage College,Austin,TX,www.vantage.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,9500,98.2276784404242,PrivacySuppressed,NaN,NaN
7586,47691101,4205801,42058,SAE Institute of Technology San Francisco,Emeryville,CA,usa.sae.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,9500,98.2276784404242,0.5454545455,NaN,NaN
7587,48065701,869423,8694,Rasmussen College - Overland Park,Overland Park,KS,rasmussen.edu,NaN,0,0,...,NaN,NaN,NaN,31000,0.553,19596.5,202.623021111344,0.3194797716,NaN,NaN
7588,48154401,4220901,42209,National Personal Training Institute of Cleveland,Highland Heights,OH,nptiohio.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
7589,48387801,4223701,42237,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,www.bamasf.com/,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,6336,65.5126916419503,NaN,NaN,NaN
7590,48400201,4228101,42281,High Desert Medical College,Lancaster,CA,www.highdesertmedicalcollege.org/,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,7521,77.76530205794,NaN,NaN,NaN
7591,48414501,4232401,42324,Vantage College-San Antonio,San Antonio,TX,www.vantage.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,10849.5,112.181178656777,NaN,NaN,NaN
7592,48621101,4215601,42156,American Institute of Pharmaceutical Technolog...,Newark,NJ,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN

In [20]:
df.index=df['UNITID']

In [21]:
df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,INSTURL,NPCURL,HCM2,PREDDEG,...,RET_PTL4_POOLED_SUPP,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,100654,100200,1002,Alabama A & M University,Normal,AL,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,0,3,...,NaN,0.8159,0.0877,29900,0.453,35000,361.891446885773,0.2458495231,NaN,0.3303
100663,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,0,3,...,NaN,0.5218,0.2363,40200,0.669,21500,222.304745944118,0.5199110572,NaN,0.5504
100690,100690,2503400,25034,Amridge University,Montgomery,AL,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,0,3,...,NaN,0.8781,0.8571,40100,0.658,23000,237.814379382079,0.2331002331,NaN,PrivacySuppressed
100706,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,www.uah.edu,finaid.uah.edu/,0,3,...,NaN,0.4589,0.2255,45600,0.685,23500,242.984257194733,0.5490029699,NaN,0.4776
100724,100724,100500,1005,Alabama State University,Montgomery,AL,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,0,3,...,NaN,0.7692,0.0974,26700,0.393,32091,331.813097771753,0.1963538553,NaN,0.2663
100751,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,0,3,...,NaN,0.4059,0.0810,42700,0.695,23750,245.56919610106,0.5911430119,NaN,0.6638
100760,100760,100700,1007,Central Alabama Community College,Alexander City,AL,www.cacc.edu,www.cacc.edu/NetPriceCalculator/14-15/npcalc.html,0,2,...,0.51948376623376,0.3574,0.2630,27200,0.466,9388,97.0696258103897,0.263502455,0.1722,NaN
100812,100812,100800,1008,Athens State University,Athens,AL,www.athens.edu,https://24.athens.edu/apex/prod8/f?p=174:1:394...,0,3,...,NaN,0.6512,0.6774,38500,0.653,18534,191.637030759455,0.4942462601,NaN,NaN
100830,100830,831000,8310,Auburn University at Montgomery,Montgomery,AL,www.aum.edu,www.aum.edu/current-students/financial-informa...,0,3,...,NaN,0.5584,0.2257,33500,0.616,22192.5,229.465026714643,0.4162696959,NaN,0.2115
100858,100858,100900,1009,Auburn University,Auburn,AL,www.auburn.edu,www.auburn.edu/admissions/money-matters.html,0,3,...,NaN,0.3470,0.0427,47100,0.741,21500,222.304745944118,0.731666973,NaN,0.7188
100937,100937,101200,1012,Birmingham Southern College,Birmingham,AL,www.bsc.edu/,www.bsc.edu/fp/np-calculator.cfm,0,3,...,NaN,0.4633,0.0141,45600,0.637,26850,277.622438539514,0.747826087,NaN,0.627
101028,101028,1218200,12182,Chattahoochee Valley Community College,Phenix City,AL,www.cv.edu,https://external.cv.edu/npc/npcalc.htm,0,2,...,0.25830463576158,0.3058,0.3604,26300,0.41,9389.5,97.0851354438277,0.2684824903,0.1376,NaN
101073,101073,1055400,10554,Concordia College Alabama,Selma,AL,www.ccal.edu/,www.ccal.edu/admissions/net-pricing-calculator/,0,2,...,NaN,0.9249,0.1294,20600,0.356,36870,381.226789905099,0.1184834123,NaN,0.1458
101116,101116,1303906,13039,South University-Montgomery,Montgomery,AL,www.southuniversity.edu/montgomery#location=Mo...,tcc.noellevitz.com/edmc/South Net Price Calcul...,0,3,...,NaN,0.7304,0.6109,30300,0.58,25000,258.493890632695,0.226137931,NaN,0.0792
101143,101143,101500,1015,Enterprise State Community College,Enterprise,AL,www.escc.edu,www.escc.edu/NetPrice/npcalc.htm,0,2,...,0.36528502994011,0.2128,0.2896,29800,0.518,7155,73.9809514990774,0.4375634518,0.1026,NaN
101161,101161,106000,1060,James H Faulkner State Community College,Bay Minette,AL,www.faulknerstate.edu,www.faulknerstate.edu,0,2,...,0.3501181619256,0.5107,0.2598,28700,0.475,11000,113.737311878385,0.3568502503,0.1146,NaN
101189,101189,100300,1003,Faulkner University,Montgomery,AL,www.faulkner.edu,www.faulkner.edu/net-price-calculator-form/,0,3,...,NaN,0.7105,0.4353,35900,0.614,21750,224.889684850445,0.3014899211,NaN,0.2553
101240,101240,101700,1017,Gadsden State Community College,Gadsden,AL,www.gadsdenstate.edu,www.gadsdenstate.edu/net-price-calculator,0,1,...,0.43215794573643,0.0000,0.3320,25400,0.379,PrivacySuppressed,PrivacySuppressed,NaN,0.1568,NaN
101277,101277,4187200,41872,New Beginning College of Cosmetology,Albertville,AL,www.nbccosmetology.com,www.nbccosmetology.com/npcalc.htm,0,1,...,PrivacySuppressed,0.5749,0.2747,NaN,NaN,5500,56.8686559391929,0.4,0.7155,NaN
101286,101286,101800,1018,George C Wallace State Community College-Dothan,Dothan,AL,www.wallace.edu,www.wallace.edu/net_price_calculator.aspx,0,2,...,0.43297406593406,0.0000,0.3422,24800,0.374,PrivacySuppressed,PrivacySuppressed,NaN,0.1721,NaN
101295,101295,787100,7871,George C Wallace State Community College-Hance...,Hanceville,AL,www.wallacestate.edu,www.wallacestate.edu/Financial-Aid/Net-Price-C...,0,2,...,0.45582165242165,0.3915,0.2671,31100,0.537,11000,113.737311878385,0.4402676011,0.2923,NaN
101301,101301,569900,5699,George C Wallace State Community College-Selma,Selma,AL,www.wccs.edu,wccs.edu/home/admissions/financial-aid/net-pri...,0,2,...,0.391665,0.0000,0.2753,23100,0.376,PrivacySuppressed,PrivacySuppressed,NaN,0.1879,NaN
101365,101365,962107,9621,Herzing University-Birmingham,Birmingham,AL,www.herzing.edu/,www.herzing.edu/financial-aid/net-price-calcul...,0,1,...,NaN,0.7219,0.7147,40300,0.566,23713.5,245.191795020736,0.2771250864,NaN,0.4118
101435,101435,101900,1019,Huntingdon College,Montgomery,AL,www.huntingdon.edu,hawk.huntingdon.edu/oiac/netpricecalculator/np...,0,3,...,NaN,0.6862,0.2196,36800,0.612,26477.5,273.770879569087,0.4992657856,NaN,0.4327
101453,101453,2199700,21997,Heritage Christian University,Florence,AL,www.hcu.edu,www.hcu.edu/netpricecalculator/,0,3,...,NaN,0.3226,0.5862,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,NaN,PrivacySuppressed
101462,101462,526000,5260,J F Drake State Community and Technical College,Huntsville,AL,www.drakestate.edu,www.drakestate.edu/admissions/net_price_calcul...,0,2,...,0.25640064102564,0.0000,0.4769,22200,0.369,PrivacySuppressed,PrivacySuppressed,NaN,0.1246,NaN
101480,101480,102000,1020,Jacksonville State University,Jacksonville,AL,www.jsu.edu/,www.jsu.edu/finaid/,0,3,...,NaN,0.6746,0.1814,35000,0.548,23250,240.399318288406,0.3945111492,NaN,0.3057
101499,101499,102100,1021,Jefferson Davis Community College,Brewton,AL,www.jdcc.edu,www.jdcc.edu/netpricecalculator/,0,2,...,0.42859238095238,0.0000,0.3843,24100,0.452,PrivacySuppressed,PrivacySuppressed,NaN,0.2427,NaN
101505,101505,102200,1022,Jefferson State Community College,Birmingham,AL,www.jeffstateonline.com,www.jeffersonstate.edu/financial-aid/net-price...,0,2,...,0.44684917891097,0.2156,0.3118,30100,0.534,8500,87.8879228151164,0.4520738933,0.0609,NaN
101514,101514,101300,1013,John C Calhoun State Community College,Tanner,AL,www.calhoun.edu,https://calhoun.edu/student-resources/financia...,0,2,...,0.43881048689138,0.2877,0.3488,27300,0.454,11000,113.737311878385,0.3851002865,0.1408,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45891902,45891902,145946,1459,Strayer University-Morrow Campus,Morrow,GA,www.strayer.edu/georgia/morrow,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45891903,45891903,145952,1459,Strayer University-Roswell Campus,Roswell,GA,www.strayer.edu/georgia/roswell,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45891904,45891904,145959,1459,Strayer University-Douglasville Campus,Douglasville,GA,www.strayer.edu/georgia/douglasville,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45891905,45891905,145965,1459,Strayer University-Lithonia Campus,Lithonia,GA,www.strayer.edu/georgia/lithonia,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45891906,45891906,145971,1459,Strayer University-Savannah Campus,Savannah,GA,www.strayer.edu/georgia/savannah,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45891907,45891907,145972,1459,Strayer University-Augusta Campus,Augusta,GA,www.strayer.edu/georgia/augusta,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45891908,45891908,145996,1459,Strayer University-Columbus,Columbus,GA,www.strayer.edu/georgia/columbus,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45896401,45896401,145945,1459,Strayer University-Columbia Campus,Columbia,SC,www.strayer.edu/south-carolina/columbia,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45896402,45896402,145954,1459,Strayer University-Charleston Campus,North Charleston,SC,www.strayer.edu/south-carolina/charleston,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45897301,45897301,145990,1459,Strayer University-Irving,Irving,TX,www.strayer.edu/texas/irving,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45897302,45897302,145992,1459,Strayer University-Katy,Houston,TX,www.strayer.edu/texas/katy,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45897303,45897303,145994,1459,Strayer University-Northwest Houston,Houston,TX,www.strayer.edu/texas/northwest-houston,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45897304,45897304,145995,1459,Strayer University-Plano,Plano,TX,www.strayer.edu/texas/plano,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45897305,45897305,10145900,1459,Strayer University-Cedar Hill,Cedar Hill,TX,www.strayer.edu/texas/cedar-hill,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45897306,45897306,10145901,1459,Strayer University-North Dallas,Dallas,TX,www.strayer.edu/texas/north-dallas,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45897307,45897307,10145908,1459,Strayer University-San Antonio,San Antonio,TX,www.strayer.edu/texas/san-antonio,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45897308,45897308,10145909,1459,Strayer University-Stafford,Stafford,TX,www.strayer.edu/texas/stafford,NaN,0,0,...,NaN,NaN,NaN,47300,0.667,34891,360.764413522615,0.2339988027,NaN,NaN
45920401,45920401,4169701,41697,Unitek College,Fremont,CA,www.unitekcollege.edu/,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,9500,98.2276784404242,0.6731391586,NaN,NaN
47503301,47503301,4208601,42086,Relay Graduate School of Education - Newark,Newark,NJ,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503302,47503302,4208602,42086,Relay Graduate School of Education - New Orleans,New Orleans,LA,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47647001,47647001,4088301,40883,WestMed College - Merced,Merced,CA,www.westmedcollege.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,10093,104.359153526231,0.5555555556,NaN,NaN
47657701,47657701,4184801,41848,Vantage College,El Paso,TX,www.vantage.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,9500,98.2276784404242,PrivacySuppressed,NaN,NaN
47657702,47657702,4184802,41848,Vantage College,Austin,TX,www.vantage.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,9500,98.2276784404242,PrivacySuppressed,NaN,NaN
47691101,47691101,4205801,42058,SAE Institute of Technology San Francisco,Emeryville,CA,usa.sae.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,9500,98.2276784404242,0.5454545455,NaN,NaN
48065701,48065701,869423,8694,Rasmussen College - Overland Park,Overland Park,KS,rasmussen.edu,NaN,0,0,...,NaN,NaN,NaN,31000,0.553,19596.5,202.623021111344,0.3194797716,NaN,NaN
48154401,48154401,4220901,42209,National Personal Training Institute of Cleveland,Highland Heights,OH,nptiohio.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
48387801,48387801,4223701,42237,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,www.bamasf.com/,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,6336,65.5126916419503,NaN,NaN,NaN
48400201,48400201,4228101,42281,High Desert Medical College,Lancaster,CA,www.highdesertmedicalcollege.org/,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,7521,77.76530205794,NaN,NaN,NaN
48414501,48414501,4232401,42324,Vantage College-San Antonio,San Antonio,TX,www.vantage.edu,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,10849.5,112.181178656777,NaN,NaN,NaN
48621101,48621101,4215601,42156,American Institute of Pharmaceutical Technolog...,Newark,NJ,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN

In [22]:
ipl=pd.read_csv("Ball_by_Ball.csv")

In [23]:
ipl

,Match_Id,Innings_Id,Over_Id,Ball_Id,Team_Batting_Id,Team_Bowling_Id,Striker_Id,Striker_Batting_Position,Non_Striker_Id,Bowler_Id,Batsman_Scored,Extra_Type,Extra_Runs,Player_dissimal_Id,Dissimal_Type,Fielder_Id
0,335987,1,1,1,1,2,1,1,2,14,0,legbyes,1,,,
1,335987,1,1,2,1,2,2,2,1,14,0,,,,,
2,335987,1,1,3,1,2,2,2,1,14,0,wides,1,,,
3,335987,1,1,4,1,2,2,2,1,14,0,,,,,
4,335987,1,1,5,1,2,2,2,1,14,0,,,,,
5,335987,1,1,6,1,2,2,2,1,14,0,,,,,
6,335987,1,1,7,1,2,2,2,1,14,0,legbyes,1,,,
7,335987,1,2,1,1,2,2,2,1,15,0,,,,,
8,335987,1,2,2,1,2,2,2,1,15,4,,,,,
9,335987,1,2,3,1,2,2,2,1,15,4,,,,,
10,335987,1,2,4,1,2,2,2,1,15,6,,,,,
11,335987,1,2,5,1,2,2,2,1,15,4,,,,,
12,335987,1,2,6,1,2,2,2,1,15,0,,,,,
13,335987,1,3,1,1,2,1,1,2,14,0,,,,,
14,335987,1,3,2,1,2,1,1,2,14,0,,,,,
15,335987,1,3,3,1,2,1,1,2,14,0,legbyes,1,,,
16,335987,1,3,4,1,2,2,2,1,14,4,,,,,
17,335987,1,3,5,1,2,2,2,1,14,1,,,,,
18,335987,1,3,6,1,2,1,1,2,14,0,,,,,
19,335987,1,4,1,1,2,2,2,1,13,0,wides,5,,,
20,335987,1,4,2,1,2,2,2,1,13,6,,,,,
21,335987,1,4,3,1,2,2,2,1,13,0,legbyes,1,,,
22,335987,1,4,4,1,2,1,1,2,13,4,,,,,
23,335987,1,4,5,1,2,1,1,2,13,0,,,,,
24,335987,1,4,6,1,2,1,1,2,13,1,,,,,
25,335987,1,4,7,1,2,2,2,1,13,6,,,,,
26,335987,1,5,1,1,2,1,1,2,14,4,,,,,
27,335987,1,5,2,1,2,1,1,2,14,1,,,,,
28,335987,1,5,3,1,2,2,2,1,14,4,,,,,
29,335987,1,5,4,1,2,2,2,1,14,0,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136560,981024,2,16,1,2,11,354,4,32,385,1,,,,,
136561,981024,2,16,2,2,11,32,5,354,385,1,,,,,
136562,981024,2,16,3,2,11,354,4,32,385,0,,,354,bowled,
136563,981024,2,16,4,2,11,369,6,32,385,0,,,,,
136564,981024,2,16,5,2,11,369,6,32,385,1,,,,,
136565,981024,2,16,6,2,11,32,5,369,385,1,,,,,
136566,981024,2,17,1,2,11,32,5,369,460,0,,,,,
136567,981024,2,17,2,2,11,32,5,369,460,2,,,,,
136568,981024,2,17,3,2,11,32,5,369,460,0,,,32,caught,163
136569,981024,2,17,4,2,11,369,6,255,460,1,,,,,
136570,981024,2,17,5,2,11,255,7,369,460,6,,,,,
136571,981024,2,17,6,2,11,255,7,369,460,1,,,,,
136572,981024,2,18,1,2,11,255,7,369,299,0,,,,,
136573,981024,2,18,2,2,11,255,7,369,299,1,,,,,
136574,981024,2,18,3,2,11,369,6,255,299,1,,,,,
136575,981024,2,18,4,2,11,255,7,369,299,0,,,,,
136576,981024,2,18,5,2,11,255,7,369,299,0,legbyes,1,,,
136577,981024,2,18,6,2,11,369,6,255,299,4,,,,,
136578,981024,2,19,1,2,11,255,7,369,460,1,,,255,run out,394
136579,981024,2,19,2,2,11,434,8,369,460,2,,,,,
136580,981024,2,19,3,2,11,434,8,369,460,0,,,,,
136581,981024,2,19,4,2,11,434,8,369,460,0,legbyes,1,,,
136582,981024,2,19,5,2,11,369,6,434,460,2,,,,,
136583,981024,2,19,6,2,11,369,6,434,460,6,,,,,
136584,981024,2,20,1,2,11,434,8,369,299,1,,,,,
136585,981024,2,20,2,2,11,369,6,434,299,2,,,,,
136586,981024,2,20,3,2,11,369,6,434,299,0,,,434,run out,183
136587,981024,2,20,4,2,11,140,9,369,299,0,legbyes,1,,,
136588,981024,2,20,5,2,11,369,6,140,299,1,,,,,
136589,981024,2,20,6,2,11,140,9,369,299,4,,,,,